# Generated by Django 6.0.1 on 2026-01-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='failure_reason',
            new_name='fail_reason',
        ),
    ]
