# Generated by Django 6.0 on 2026-01-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan_text', models.CharField(default='Boost Your YouTube Channel', max_length=255)),
                ('slogan_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('intro_text', models.TextField(default='We help you grow...')),
                ('intro_flowchart', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('case_1_img', models.ImageField(blank=True, null=True, upload_to='cases/')),
                ('case_2_img', models.ImageField(blank=True, null=True, upload_to='cases/')),
                ('case_3_img', models.ImageField(blank=True, null=True, upload_to='cases/')),
                ('case_4_img', models.ImageField(blank=True, null=True, upload_to='cases/')),
                ('case_text', models.TextField(default='Our success stories')),
            ],
            options={
                'verbose_name': 'Home Page Configuration',
            },
        ),
    ]
