# Generated by Django 6.0.1 on 2026-01-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_seoarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageconfig',
            name='case_text',
            field=models.TextField(blank=True, default='Our success stories'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='intro_text',
            field=models.TextField(blank=True, default='We help you grow...'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='slogan_text',
            field=models.CharField(blank=True, default='Boost Your YouTube Channel', max_length=255),
        ),
    ]
