# Generated by Django 6.0.1 on 2026-01-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_homepageconfig_case_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoarticle',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_covers/'),
        ),
    ]
