# Generated by Django 6.0.1 on 2026-01-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_cookie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
